CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA r2schema;

CREATE TABLE APP_USER (
    APP_USERID UUID default uuid_generate_v4(),
    USERNAME VARCHAR(100) not null,
    FIRST_NAME VARCHAR (50) not null,
    LAST_NAME VARCHAR (50) not null,
    ACCT_LOCKED BOOLEAN not null default false,
    ACTIVE BOOLEAN not null default true,
    CREATED_DATE DATE not null default now(),
    PRIMARY KEY(APP_USERID)
);


CREATE TABLE APP_ACCOUNT(
   ACCT_ID UUID default uuid_generate_v4(),
   EMAIL VARCHAR(100) not null,
   PASSWORD VARCHAR (250) not null,
   ACCT_LOCKED BOOLEAN not null default false,
   ACTIVE BOOLEAN not null default true,
   CREATED_DATE DATE NOT NULL DEFAULT now(),
   CREATED_BY VARCHAR(50),
   MODIFIED_DATE DATE,
   MODIFIED_BY VARCHAR(50),
   PRIMARY KEY(ACCT_ID)
);


CREATE TABLE APP_ACCT_USER(
  ACCT_USERID UUID DEFAULT uuid_generate_v4(),
  ACCT_ID UUID NOT NULL,
  FIRST_NAME VARCHAR (50) not null,
  LAST_NAME VARCHAR (50) not null,
  CREATED_DATE DATE NOT NULL DEFAULT now(),
  CREATED_BY VARCHAR(50),
  MODIFIED_DATE DATE,
  MODIFIED_BY VARCHAR(50),
  PRIMARY KEY(ACCT_USERID),
  FOREIGN KEY (ACCT_ID) REFERENCES APP_ACCOUNT(ACCT_ID)
);
